### ISSUE TITLE
請問是否可以啟用 realme_GT2pro-AndroidS-kernel-source  的Issues 選項

### ISSUE THREAD

**Issue by skysumbra** [onichan0923/smiley-moon#2]
你好，
由於你的項目 realme_GT2pro-AndroidS-kernel-source 中沒有Issues 選項可以使用，
所以在其他項目中提問，請問是否可以啟用realme_GT2pro-AndroidS-kernel-source 中Issues 選項，想要請教device tree 內設計問題，謝謝。

**Comment by onichan0923** [comment]
那个dt直接克隆自官方，或许你可以去官方那里开issue
